### ISSUE TITLE
Generated SaveFieldsToBuf does not clear tmpBuf before it's reused

### ISSUE THREAD

**Issue by IkeMurami** [modersohn/ProtoBufGenerator#25]
**The example:**

```
metadata {
  shareInfo {
    myFlag: true
  }
  photoInfo {
    myFlag: true
    data {
      myFlag: true
    }
  }
  cameraInfo {
    myFlag: true
    5 {
      4: 1
    }
  }
}
myFlag: true
```

**The problem:**
cameraInfo has excess field number 5. The original proto file doesn't have field number 5.
I discovered that it happens because the buffer wasn't cleaned up after serializing the photoInfo object.
It is the photoInfo which has field number 5 (called data) and subfield number 4 (called myFlag).

**Fix:**

1. pbOutput.pas
Add public property Buffer: TSegmentBuffer to TProtoBufOutput

2. uAbstractProtoBufClasses.pas
```
procedure TAbstractProtoBufClass.SaveToBuf(ProtoBuf: TProtoBufOutput);
begin
  ProtoBuf.Buffer.Clear;  // <-- clean up the buffer here
  SaveFieldsToBuf(ProtoBuf);
end;
```

**Comment by modersohn** [comment]
The example seems not to be one of the examples within this repository, correct?

From what I understand, I don't agree with your fix. Why would SaveToBuf need to clear ProtoBuf? Whoever calls SaveToBuf needs to make sure a proper ProtoBufOutput class without any left-overs is passed.

Can you reproduce the behaviour with any of the provided examples? Or show the modifications necessary that it also exposes the problem?

**Comment by IkeMurami** [comment]
OK, here's more detailed explanation. I've prepared the example: [example.zip](https://github.com/modersohn/ProtoBufGenerator/files/2904434/example.zip)

1. Compile the example.proto file.
2. Create new project and call the following procedure. Then backup the out.bin file, add my fix and call it again:
```
procedure Test;
var
  robot: TRobot;
  filestr: TFileStream;
begin
  robot := TRobot.Create;

  robot.FieldHasValue[robot.tag_soft] := True;
  robot.soft.vendor := 'Google';
  robot.soft.FieldHasValue[robot.soft.tag_ver] := True;
  robot.soft.ver.major := 0;
  robot.soft.ver.minor := 1;
  robot.soft.ver.release := 2;
  robot.soft.ver.build := 3;

  robot.FieldHasValue[robot.tag_hard] := True;
  robot.hard.vendor := 'Huawei';

  filestr := TFileStream.Create('out.bin', fmCreate);
  try
    robot.SaveToStream(filestr);
  finally
    FreeAndNil(filestr);
  end;
end;
```
3. Call protoc.exe for the both files:
```
protoc.exe --decode=example.Robot example.proto < out_nofix.bin > out_nofix.txt
protoc.exe --decode=example.Robot example.proto < out_fix.bin > out_fix.txt
```
4. You'll see the difference:
The object "hard" has an extra field number 2 which was not defined in the source proto.
That object is technically a grabage left after serialization of the object "soft".
That's why you have to cleanup the buffer before serializing the object.
```
procedure TRobot.SaveFieldsToBuf(ProtoBuf: TProtoBufOutput);
var
  tmpBuf: TProtoBufOutput;
begin
  inherited;
  tmpBuf:= TProtoBufOutput.Create;
  try
    if FieldHasValue[tag_soft] then
    begin
      Fsoft.SaveToBuf(tmpBuf);  // <-- "soft" was serialized to tmpBuf.
      ProtoBuf.writeMessage(tag_soft, tmpBuf); // <-- tmpBuf was written to stream.
    end;
    if FieldHasValue[tag_hard] then
    begin
      Fhard.SaveToBuf(tmpBuf); // <-- "hard" was serialized to the same tmpBuf wich still has data from "soft".
      ProtoBuf.writeMessage(tag_hard, tmpBuf); // <-- tmpBuf was written to stream with grabage.
    end;
  finally
    tmpBuf.Free
  end;
end;
```
That's why I suggest to clean tmpBuf in the SaveToBuf procedure.
I noticed this bug when I had to work with very large proto with multiple objects and this bug increased the output data size from alleged 1KB to about 300KB.

**Comment by modersohn** [comment]
Okay, thanks for the example. I think the error is in the generated code:

```
procedure TRobot.SaveFieldsToBuf(ProtoBuf: TProtoBufOutput);
var
  tmpBuf: TProtoBufOutput;
begin
  inherited;
  tmpBuf:= TProtoBufOutput.Create;
  try
    if FieldHasValue[tag_soft] then
    begin
      Fsoft.SaveToBuf(tmpBuf);
      ProtoBuf.writeMessage(tag_soft, tmpBuf);
    end;
    if FieldHasValue[tag_hard] then
    begin
      Fhard.SaveToBuf(tmpBuf);
      ProtoBuf.writeMessage(tag_hard, tmpBuf);
    end;
  finally
    tmpBuf.Free
  end;
end;
```

This code reuses tmpBuf without clearing it. This re-usage was introduced when I was working on issue #4.

But I still disagree with your fix. If I pass something to a save method (be it a ProtoBuf or a Stream or similar), I expect that that container is used without touching any previous content. I haven't verified, but I suspect your fix would break writing of nested messages.

**Comment by modersohn** [comment]
I've pushed a fix to master. Please get back to me if you can confirm this fixes the issue, so I can create a pull request for the original kami-soft repository

**Comment by IkeMurami** [comment]
I confirm that your fix has resolved the issue, Thank you!
